@startuml
struct Asset
struct AssetDefinition

struct Id {
  definition_id
  account_id
}

enum Mintable {
  Infinitely
  Once
  Not
}

enum AssetValue {
  Quantity
  BigQuantity
  Fixed
  Store
}

Asset -- AssetDefinition
Asset -- Id
AssetDefinition -- Mintable
AssetDefinition -- AssetValue 
AssetDefinition -- Id

Asset : id {Id}
Asset : value

AssetDefinition : id {Id}
AssetDefinition : value_type {AssetValueType}
AssetDefinition : mintable {Mintable}
AssetDefinition : metadata
@enduml