@startuml

object domain_wonderland {
  id = "wonderland"
}
object account_alice #aliceblue {
  id = "alice@wonderland"
}
object account_mad_hatter #aliceblue {
  id = "mad_hatter@wonderland"
}

object asset_rose #pink {
  id = "rose#wonderland"
}

domain_wonderland *-- account_alice : registered in
domain_wonderland *-- asset_rose : registered in
account_alice *-- asset_rose : registered by
domain_wonderland *-- account_mad_hatter : registered in

object domain_narnia {
  id = "narnia"
}

object account_lion #aliceblue {
  id = "lion@narnia"
}

domain_narnia *-- account_lion : registered in

@enduml
