@startuml

struct MetadataChanged<ID> {
    target_id: ID
    key: Name
    value: Box<Value>
}

struct AccountMetadataChanged<AccountId>
struct AssetMetadataChanged<AssetId>
struct AssetDefinitionMetadataChanged<AssetDefinitionId>
struct DomainMetadataChanged<DomainId>

MetadataChanged --> AccountMetadataChanged
MetadataChanged --> AssetMetadataChanged
MetadataChanged --> AssetDefinitionMetadataChanged
MetadataChanged --> DomainMetadataChanged

@enduml
