@startuml
object event_trigger {
  {Action<F: Filter>}
}

object time_trigger {
  {Action<TimeEventFilter>}
}
object data_trigger {
  {Action<DataEventFilter>}
}
object by_call_trigger {
  {Action<ExecuteTriggerEventFilter>}
}
object pipeline_trigger {
  {Action<PipelineEventFilter>}
}

event_trigger *-- time_trigger
event_trigger *-- by_call_trigger
event_trigger *-- data_trigger
event_trigger *-- pipeline_trigger

@enduml
