@startuml

struct Trigger<F: Filter>

struct time_trigger<TimeEventFilter>
struct data_trigger<DataEventFilter>
struct by_call_trigger<ExecuteTriggerEventFilter>
struct pipeline_trigger<PipelineEventFilter>

struct precommit_trigger<TimeEventFilter(ExecutionTime::PreCommit)>
struct scheduled_trigger<TimeEventFilter(ExecutionTime::Schedule(schedule))>

Trigger --> time_trigger
Trigger --> by_call_trigger
Trigger --> data_trigger
Trigger --> pipeline_trigger

time_trigger --> precommit_trigger 
time_trigger --> scheduled_trigger

@enduml
